# Generated by Django 4.1 on 2022-08-22 23:52

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Communication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("owner_name", models.CharField(editable=False, max_length=250)),
                ("owner_email", models.EmailField(max_length=250, unique=True)),
                (
                    "owner_cpf",
                    models.CharField(
                        editable=False,
                        max_length=15,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^([0-9]{3}[\\.][0-9]{3}[\\.][0-9]{3}[-][0-9]{2})$",
                                message="Try the following pattern: XXX.XXX.XXX-XX",
                            )
                        ],
                    ),
                ),
                ("latitude", models.FloatField(editable=False)),
                ("longitude", models.FloatField(editable=False)),
                ("type", models.CharField(max_length=50)),
                ("date", models.DateField(editable=False)),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("CHUVA_EXCESSIVA", "CHUVA_EXCESSIVA"),
                            ("GEADA", "GEADA"),
                            ("GRANIZO", "GRANIZO"),
                            ("SECA", "SECA"),
                            ("VENDAVAL", "VENDAVAL"),
                            ("RAIO", "RAIO"),
                        ],
                        editable=False,
                        max_length=50,
                    ),
                ),
            ],
            options={
                "db_table": "communication",
            },
        ),
    ]
