# Generated by Django 4.1 on 2022-08-23 00:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communication",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="communication",
            name="event",
            field=models.CharField(
                choices=[
                    ("CHUVA_EXCESSIVA", "CHUVA_EXCESSIVA"),
                    ("GEADA", "GEADA"),
                    ("GRANIZO", "GRANIZO"),
                    ("SECA", "SECA"),
                    ("VENDAVAL", "VENDAVAL"),
                    ("RAIO", "RAIO"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="communication",
            name="latitude",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="communication",
            name="longitude",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="communication",
            name="owner_cpf",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        "^([0-9]{3}[\\.][0-9]{3}[\\.][0-9]{3}[-][0-9]{2})$",
                        message="Try the following pattern: XXX.XXX.XXX-XX",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="communication",
            name="owner_email",
            field=models.EmailField(max_length=250),
        ),
        migrations.AlterField(
            model_name="communication",
            name="owner_name",
            field=models.CharField(max_length=250),
        ),
    ]
